language: c
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get-install libmpfr-dev
install:
  - ./.install-deps.sh
script:
  - make -j4 test PREFIX=$HOME/deps
